services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    environment:
      - FRONTEND_URL=https://cloudenoch.com
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb+srv:default@cluster0.3oo7kyd.mongodb.net/resumeStats?retryWrites=true&w=majority}
    restart: always
