services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - ./api/.env
    environment:
      - FRONTEND_URL=https://cloudenoch.com
      - MONGODB_URI=mongodb://mongodb:27017/resumeStats
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
