services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "8000"
    env_file:
      - ./api/.env
    environment:
      - FRONTEND_URL=https://cloudenoch.com
    restart: always
