version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@2.0.3
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Check npm and node versions
          command: |
            npm --version
            node --version
      - run:
          name: List package.json content
          command: cat package.json
      - run:
          name: Install dependencies with verbose logging
          command: npm install --verbose
      - run:
          name: Run linter
          command: npx eslint .
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: build
          to: 's3://${AWS_S3_BUCKET}'
      - run:
          name: Invalidate CloudFront
          command: |
            aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
