version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@2.0.3
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.19
    steps:
      - checkout
      - run:
          name: Output package.json contents
          command: cat package.json
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: List installed packages
          command: yarn list --depth=0
      - run:
          name: Check yarn and node versions
          command: |
            yarn --version
            node --version
      - run:
          name: Run linter
          command: yarn run eslint .
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build application
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: build
          to: 's3://${AWS_S3_BUCKET}'
      - run:
          name: Invalidate CloudFront
          command: |
            aws cloudfront create-invalidation --distribution-id ${AWS_CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main